branches:
  except:
  - localization
osx_image: xcode11.1
language: objective-c
xcode_workspace: Zap.xcworkspace
xcode_scheme: Zap
cache: bundler
addons:
  homebrew:
    packages:
    - graphicsmagick
git:
  quiet: true
  depth: 3
notifications:
  email:
    on_success: never
    on_failure: change
install:
  - bundle install
  - carthage bootstrap --platform iOS
stages:
  - test
  - name: deploy
    if: tag ~= ^v.*
jobs:
  include:
    - stage: test
      script: bundle exec fastlane tests
      after_success:
        - bash <(curl -s https://codecov.io/bash) -J 'Library' -J 'Lightning'
    - stage: deploy
      script: bundle exec fastlane testnet
      name: "Deploy Testflight Testnet"
    - script: bundle exec fastlane mainnet
      name: "Deploy Testflight Mainnet"
    - script: bundle exec fastlane release
      name: "Deploy Appstore Testnet"
env:
  global:
  # MATCH_GIT_BASIC_AUTHORIZATION
  - secure: TC+Vfo4vq/XBPOhAiLgaM+lLoDthf8Fkin1HEGmqw+la0Z16zn2jo6dSobOS9MKF/KeBwx8OAk0FX4LCPP9tTRiJhZP6/PwCIpGsdg4ahWnu0MtsJs7y5Qo07sSd+fkUMkxDdBWCGLu7d09sD5aIkcymlFIlfn+AY4lwBDDzDDSZt/jSSu4Io+zMr5UpGk4SdrcYn1ZmdJBaEKTGZal7MIm5xm3LUQSqrqo2NCRaxARHNYFhGcBgXGysO3Poknuh7Aw5Fw5tVx+eX2K1dza67RTCjef4IgqlX3z0AN6KEJEJF7WotS5t0gc3Xup85pxdPj7HyZc15B120PcG+iVcHi4uCVA+eYFal3btv2cPDin/gqVnompd8UkV/RGnqQ1KbwbStijGLZVArmkMnkwxrQEDyuGNhuOQyXFIBngHEXAF+skb89nQjpILnGDbEzJIIojYCMraeJgHZYBIdFRLgRNhasYCgRBfadrxoQFSGFM1hmFmRK9Q/rKBG069pfSCuO4yHow+QKZ7WGykhr8p3pjhhk27VXkFdpFbpM2xq/JflyFcwYtXN1HFX3Ue+00qwfiCT7Ba67mfWGEkDm8xVD+26Fzve8ufvVZ+SY+1AskU+KhRtjM+Rw5O+QS5QqRzGPBqoJOkSuNFu54rhZ9fM8Twaq9z3ZQTh6K8c/wtLUo=
  # MATCH_PASSWORD
  - secure: RQ71U9thQM8siYKWuxN6JCXD14g3e8DE+sIpgQ8uq5rAEhCeSq6OdlT2dTkO+SvUxx71dyN+UqWBBgsi96nEzejU4OeciAipsxkVXLdK5KcBe16ksuCQuIh/FHPzagpFsWQbkNc27SNr4z8eNHUF8tP6PbolFQARa//2GGiGyZvmiOUasRJI+Q4BBNEcRzd+d5HqD281CU60bZX61PpOf5/rnkewHrzb2oJavna3hdIaAb4eoOY1dm4eatei149tmmRNq4WUratRR4IrbS/mMojV6f2jCGdJPffMvFrC672quTrA9ccZctOauBoHqNrwL8yjXSH4DkABeiyV9qbCBmVjHiTf+j+yNr6pQncdnrEfmfFIe5G33zpqPHBqz/GBVnN7tkCD1UBZJsUw1HvN+kboDNdHG8Zw6hMJn+b08PttAK+Cg+PWIHnqf/GksD3zNHXv8OULdN2sgdLpld3RCKXBLISRomlTj3wqLYIk1u0vuIgdMfTo17wrDM943xOVSFiMCiq4i/QmgLyjkAEW7F1ug3Kj5Xbfa2IIf0vY4CjWUBmak3Y0ojbxVv/CdjSWqP7gMmn1iMBYjqL9/GgG+p6to/XU4CviY9SCOBNQcC0KrdFG3fg08NveLseOaBUYedxCJSFUzCHAvdxoiIhcT49M7MIdmjtu+hIgxoFDCYo=
  # ITUNESCONNECT_USER
  - secure: pTsuHpdrNIQ3XDu6kvgAZLhX8fcTN6ny93G14tW8Zt/Dsj0QeQBZcEpvu21aJ4y3Kxn02xevaprShYd0FjklrkQEs80f6A0/JR04FRwqZylAwU6/d4eFzjA+WvGAkkyv0m0aU4sYa0pJtWaEky/AFt+3OjzESTvpAHq0RPv/pfYgXSstznoX1/7un4ze0Rzx+iRMIMni40WpYd7W4PRCiJnX12SwoIYPuuhccdgyKVHqyUvM7iEINnsXtzo+L1MbQb/dHNpQdMPEvbX/ePOeY+2gqPICwZg5JYK424H5PGDT2foGQ20+EBc/n8MRqPxMW2F5SbSBkqO/G6lHdZ6audpovjhjzXfK5emhmyIkU3V5eVVVIHSXX0tuuuX5IoazvxG7gb9BLGgZebd5KVb7AQ2cXOuAqbOxZtMPVl7QUHHRQIkJusiEOlI6kLRYg1PR+Fw5nApdK4GV2yO0YBOjaZgz1M9/zKtsTn5NHVAjwfSZByJDYdbGD8XwwwHIiI2hILYlJzP7E5Ipb8sTJwqgEwLrHD3Gh5piSKnuWXuAFFRyj8/WRB6hTBNb5xeUcQGYduw43kGBe8FCrz4jM7dgv2JtmF7zN6nYskvHhUgeSHBZheVxKTSgCPIlHeD4o9JI1eamoY6+iTWXkvNFwmmt3kd08ZSWSBt/yrP/MGJ93GI=
  # FASTLANE_PASSWORD
  - secure: e7OfeuAyKcvrRkrNfxIMiHEwuBHIOEGT+GcNJIneSQ4NAgq4fqH7l1T6XiLKkha/lCDlYih4vctOMpxRAawmtfkHwMNcdzf6g0Syd/1YrhFhufKcxHKITiUX8xo/I0YoNn8O2NN3uNk5mLruUCLlR4G3APXwdBt99ZNeu30SngVanEaAewQYywaRwEShMICfOnMLA1q7fNQGyGNLnvj3e0/AruCtw8DX8ryyWWwriS1PMReZxzlS16jhZaVTp7OQO4XqHQSj3NoGuL9MJd6AMstgD0G8f/broPBzCBGV0m7iuv5fXPhlZGomMOez18FolEwTIq4ODxDuWYouVHL/BGg9PthmNnN4lio7tMcqXizePnd42JuQA/fh3/AhpcDbDRW3Bny5l9aRjIB0aIWjlB8+6Vw2m/FZbIXPMbHjOztmO49GGVfWUvQCuKsZqhezoPhTZYhnX4c1DvHzp4AKi7BVNmLMmcVp84eRaPrcfOIYYWp/Au4WlMIu+GQa1J3EgDOHI+24/tKNVTnx9fc/gQycVfPpxuX/K4lHMEbm3tu9ZkdIJnILwGX0qx6uogsfJptJp1T/GhyIYrMJ3UMsCg0nmN+YHHol7vy0ym7oH9Aj5hJz09atafdwF8hqvpk48J5FPyXMlbB/RmC8A2dz0/Ob5pFyHIJtWtHvtrSVHGg=
